# Generated by Django 4.2.7 on 2023-11-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_padaria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id_cliente", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField()),
                ("telefone", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="TodoList",
        ),
    ]
